name: Test
on:
  pull_request:
    branches: [master]
  push:
    branches: [master]
  schedule:
    # Run every day @9:21. 9:21 chosen randomly.
    - cron: '21 9 * * *'

jobs:
  test:
    name: Go ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: "Latest"
            go-version: '>=1.18'
            check-latest: true
          - name: "1.18"
            go-version: '1.18'
            check-latest: false
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "${{ matrix.go-version }}"
          check-latest: "${{ matrix.check-latest }}"
      - name: Test
        run: go test -v ./...
